### PR TITLE
Friendships v1

### PR DESCRIPTION
**Pull request by ahmadchata**
## Friendships v1
In this pull request, I created the following
- A user can add a friend.
- A user can see pending requests when a request is sent
- A user can either accept or reject the request.

### CODE REVIEW

**Review by Dandush03 — CHANGES_REQUESTED** [review]
# Status: :red_circle: Requre Changes :red_circle: 
### Great work, keep it up! :muscle: but we need to fix some issues;
- [x] **.ruby-version file has a different version from the one in your Gemfile** this might cause your code to break when using rbenv or any other multi-environment control  of ruby
- [ ] **Tests!:** There should be a test for everything; controller, views, model, and routes please add them.
- [ ] **Friendships Views:**
  - [x] After accepting the user I should not be able to request a new friend request, it should be marked as a friend.
  - [ ] There is a button to invite user to friendship on users list page and on the single-user page ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/user_can_see_invite_buttton.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))

- [x] **Posts timeline** includes posts written by logged-in user and their friends ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friends_timeline.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
# Happy Coding :tophat:

**Comment by ahmadchata** [comment]
## Changes made
- Change the ruby version in Gemfile to match with .ruby-version file
- Add unit and integration tests
- Friendship status now shows 'Friend' when a user accepts a friendship request
- Timeline includes posts by logged in users and friends

**Review by teekaytech — CHANGES_REQUESTED** [review]
## Status: Changes Required :warning: :vertical_traffic_light: 

### Hello team :wave:

__You've done so well in this project. You also did well in fixing the changes suggested by the last reviewer. But we still have some required changes to make before this project can be approved. Please check my comments below and fix them as appropriate.__

**[ REQUIRED CHANGES ]**

- [x] As mentioned by the previous reviewer, the posts timeline should include only posts written by logged-in user and their friends.
- At the moment, the post timeline displays all posts written by the logged-in user and other users, including those who are friends with the logged-in user and those who are not. Kindly check your logic to implement this feature.

- [x] Friendship status does not show 'Friend' when a user accepts a friendship request.
 - The friendship status only shows `Friend` for the user that sent the invitation. We still have it as `Add Friend` for the receiver (the user to who the invitation was sent) even after accepting the friend request.

- [x] You only added unit tests. Kindly add more integration/feature test suites.


* * *
**Please make the required changes and submit another review request when you are done.**

* * *

**Taofeek Olalere
[Twitter](https://twitter.com/ola_lere) | [Github](https://github.com/teekaytech) | @taofeekolalere on Slack**
__Happy Coding :smiley:__

**Comment by ahmadchata** [comment]
## Changes made
- Update timeline to show posts by logged-in users and friends
- Update friendship status to show friends when a user accepts a request
- Add integration/feature tests

**Review by voscarmv — CHANGES_REQUESTED** [review]
# Nice work so far, team. 👍 

## However, there are some changes required 👀 🧰 🔨 🔧 

- When trying to create a new post in a fresh install of your app, I've received the following error. The posts index method seems to be where the bug is. Please fix this:

image

This bug is making your app mostly unusable. I can't really test for friendships either because when I try to log out to create another account, I get the same error screen.

Please fix this!

### Submit these changes and request a new code review! 😄 👍 

### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier) 🧑‍💻🗨️🧑‍💻 
# Happy Hacking! 🧠 ⌨️ 🖱️ 🖥️

**Comment by ahmadchata** [comment]
- Fix error in posts index

**Review by voscarmv — CHANGES_REQUESTED** [review]
# Nice work so far, team. 👍 

- Good work quickly fixing the previous bug!

## However, there are some changes required 👀 🧰 🔨 🔧 

- When I try to create an empty post, I get this error. Please make sure that there is some validation method to avoid it:

image

- For some reason, the user that receives and accepts the frienship request, can not see the posts made by the friendship sender. Please make sure that the friendship receiver can see the posts made by the sender. Find this bug, and fix it.

### Submit these changes and request a new code review! 😄 👍 

### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier) 🧑‍💻🗨️🧑‍💻 
# Happy Hacking! 🧠 ⌨️ 🖱️ 🖥️

**Comment by ahmadchata** [comment]
- Fix error when trying to create empty posts
- Timeline now shows posts from friendship sender

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes :recycle: :traffic_light: 

Hi @ahmadchata, great job on this project :+1: Congratulations on fixing all the comments made by the previous TSE :+1: However, there is one important thing to fix before we proceed.
Kindly check the comments below:

- Kindly set up code linter for the project :smile:

Once this is fixed, kindly submit another code review request :+1: 

_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

**Comment by ahmadchata** [comment]
- There's code linter for the project

**Review by teekaytech — CHANGES_REQUESTED** [review]
## Status: Changes Required :warning: :vertical_traffic_light: 

### Hello @ahmadchata  :wave:

__Everthing is set here. We just have to make one last change and we should be good to go.__

**[ REQUIRED CHANGES ]**

- [ ] GitHub Actions checks are not running on your PR page.
- Yes, you've already set up the code linter, but the linter checks are not running on your pull request page. Kindly find a way to make the checks run successfully on your PR page.

That's it! 



* * *
**Please make the required changes and submit another review request when you are done.**

* * *

**Taofeek Olalere
[Twitter](https://twitter.com/ola_lere) | [Github](https://github.com/teekaytech) | @taofeekolalere on Slack**
__Happy Coding :smiley:__

**Comment by ahmadchata** [comment]
- Checks are now running on PR
- Checks are now running on PR...Phewww!!! 😅

**Review by lekegitrepo — APPROVED** [review]
## Status: Approved :heavy_check_mark:
#### You have done a good job :+1: by enabling the linter for this Pull Request. This project is Approved :white_check_mark:

#### _Reviewed by Temitayo Adeleke_

**Pull request merged**
